name: oduck
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  ionicons: ^0.2.2
  flutter_riverpod: ^2.1.3
  image_picker: 0.8.6+1
  google_fonts: ^4.0.3
  go_router: 6.0.2
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/googleLogo.png
